# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  peer:
    image: hyperledger/fabric-peer:1.4.1
    environment:
      - CORE_PEER_LOCALMSPID=BlazersMSP
      - CORE_PEER_ADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - ORDERER_ADDRESS=orderer.blazers.com:7050
      - FOODSUPPLY_CHANNEL_BLOCK_0=./foodsupplychannel_0.block
      - FOODSUPPLY_CHANNEL_BLOCK=./foodsupplychannel.block
      - CHANNEL_TX_FILE=./foodsupply-channel.tx
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID= foodsupply-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true    
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
      - CORE_METRICS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: chmod 755 * && peer node start 2> peer.log &
    networks:
      - orderer_backend_network
    volumes:
    -  /var/run/:/host/var/run/
    - ./peer_files:/opt/gopath/src/github.com/hyperledger/fabric/peer

  chaincode:
    image: hyperledger/fabric-ccenv:1.4.1
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=BlazersMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CHAINCODE_LOGGING_LEVEL=info
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    networks:
      - orderer_backend_network
    volumes:
        -  /var/run/:/host/var/run/
        - ./peer_files/application/chaincode:/opt/gopath/src/chaincode

  couchdb: 
    image: hyperledger/fabric-couchdb:0.4.15
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - orderer_backend_network
  
  couchdb.admin.blazers.com:
    container_name: couchdb.admin.blazers.com
    extends:
      service: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    
  couchdb.supplier.blazers.com:
    container_name: couchdb.supplier.blazers.com
    extends:
      service: couchdb
    ports:
      - 7984:5984
  
  couchdb.manufacturer.blazers.com:
    container_name: couchdb.manufacturer.blazers.com
    extends:
      service: couchdb
    ports:
      - 8984:5984
  
  couchdb.distributor.blazers.com:
    container_name: couchdb.distributor.blazers.com
    extends:
      service: couchdb
    ports:
      - 9984:5984
    
  couchdb.retailer.blazers.com:
    container_name: couchdb.retailer.blazers.com
    extends:
      service: couchdb
    ports:
      - 10984:5984

 
  admin.blazers.com:
    container_name: admin.blazers.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=admin.blazers
      - CORE_PEER_ADDRESS=admin.blazers.com:7051
      - CORE_PEER_CHAINCODE_ADDRESS=chaincode.admin.blazers.com:7052
      - CORE_PEER_CHAINCODE_LISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.admin.blazers.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=admin.blazers.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    command:  peer node start
    links:
      - couchdb.admin.blazers.com
    volumes:
        - ./peer_files:/opt/gopath/src/github.com/hyperledger/fabric/peer
        - ./msps/admin.blazers/msp:/etc/hyperledger/fabric/msp
        -  admin.blazers.com:/var/hyperledger/production
    ports:
      - 6051:7051
      - 6055:7055
      - 6053:7053
    depends_on:
     - couchdb.admin.blazers.com

  supplier.blazers.com:
    container_name: supplier.blazers.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=supplier.blazers
      - CORE_PEER_ADDRESS=supplier.blazers.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode.supplier.blazers.com:7052
      - CORE_PEER_CHAINCODE_ADDRESS=chaincode.supplier.blazers.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.supplier.blazers.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=supplier.blazers.com:7051
    command: ./launch-peer.sh
    links:
      - couchdb.supplier.blazers.com
    volumes:
        - ./msps/supplier.blazers/msp:/etc/hyperledger/fabric/msp
        -  supplier.blazers.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
     - couchdb.supplier.blazers.com
    
  manufacturer.blazers.com:
    container_name: manufacturer.blazers.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=manufacturer.blazers
      - CORE_PEER_ADDRESS=manufacturer.blazers.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode.manufacturer.blazers.com:7052
      - CORE_PEER_CHAINCODE_ADDRESS=chaincode.manufacturer.blazers.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.manufacturer.blazers.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=manufacturer.blazers.com:7051
    command: ./launch-peer.sh
    links:
      - couchdb.manufacturer.blazers.com
    volumes:
        - ./msps/manufacturer.blazers/msp:/etc/hyperledger/fabric/msp
        -  manufacturer.blazers.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
     - couchdb.manufacturer.blazers.com
    
  distributor.blazers.com:
    container_name: distributor.blazers.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=distributor.blazers
      - CORE_PEER_ADDRESS=distributor.blazers.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode.distributor.blazers.com:7052
      - CORE_PEER_CHAINCODE_ADDRESS=chaincode.distributor.blazers.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.distributor.blazers.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=distributor.blazers.com:7051
    command: ./launch-peer.sh
    links:
      - couchdb.distributor.blazers.com
    volumes:
        - ./msps/distributor.blazers/msp:/etc/hyperledger/fabric/msp
        -  distributor.blazers.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
     - couchdb.distributor.blazers.com
  

  retailer.blazers.com:
    container_name: retailer.blazers.com
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=retailer.blazers
      - CORE_PEER_ADDRESS=retailer.blazers.com:7051
      - CORE_PEER_CHAINCODE_LISTENADDRESS=chaincode.retailer.blazers.com:7052
      - CORE_PEER_CHAINCODE_ADDRESS=chaincode.retailer.blazers.com:7052
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.retailer.blazers.com:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=retailer.blazers.com:7051
    command: ./launch-peer.sh
    links:
      - couchdb.retailer.blazers.com
    volumes:
        - ./msps/retailer.blazers/msp:/etc/hyperledger/fabric/msp
        -  retailer.blazers.com:/var/hyperledger/production
    ports:
        - 10051:7051
        - 10053:7053
    depends_on:
        - couchdb.retailer.blazers.com


  chaincode.admin.blazers.com:
    container_name: chaincode.admin.blazers.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=admin.blazers
      - CORE_PEER_ADDRESS=admin.blazers.com:7051

    volumes:
        - ./msps/admin.blazers/msp:/etc/hyperledger/msp
    ports: 
       - 6052:7052
    depends_on:
       - admin.blazers.com
       - couchdb.admin.blazers.com
   
  chaincode.supplier.blazers.com:
    container_name: chaincode.supplier.blazers.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=supplier.blazers
      - CORE_PEER_ADDRESS=supplier.blazers.com:7051
    volumes:
      - ./msps/supplier.blazers/msp:/etc/hyperledger/msp
    ports: 
      - 7052:7052
    depends_on:
     - supplier.blazers.com
     - couchdb.supplier.blazers.com
    
  chaincode.manufacturer.blazers.com:
    container_name: chaincode.manufacturer.blazers.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=manufacturer.blazers
      - CORE_PEER_ADDRESS=manufacturer.blazers.com:7051
    volumes:
      - ./msps/manufacturer.blazers/msp:/etc/hyperledger/msp
    ports: 
      - 8052:7052
    depends_on:
     - manufacturer.blazers.com
     - couchdb.manufacturer.blazers.com

  chaincode.distributor.blazers.com:
    container_name: chaincode.distributor.blazers.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=distributor.blazers
      - CORE_PEER_ADDRESS=distributor.blazers.com:7051
    volumes:
      - ./msps/distributor.blazers/msp:/etc/hyperledger/msp
    ports: 
      - 9052:7052
    depends_on:
     - distributor.blazers.com
     - couchdb.distributor.blazers.com

  chaincode.retailer.blazers.com:
    container_name: chaincode.retailer.blazers.com
    extends:
      service: chaincode
    environment:
      - CORE_PEER_ID=retailer.blazers
      - CORE_PEER_ADDRESS=retailer.blazers.com:7051
    volumes:
      - ./msps/retailer.blazers/msp:/etc/hyperledger/msp
    ports: 
      - 10052:7052
    depends_on:
      - retailer.blazers.com
      - couchdb.retailer.blazers.com


  cli.blazers.com:
    container_name: cli.blazers.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - FOODSUPPLY_CHANNEL_BLOCK_0=./foodsupplychannel_0.block
      - CHANNEL_TX_FILE=./foodsupply-channel.tx
      - ORDERER_ADDRESS=orderer.blazers.com:7050
      - CORE_PEER_ID=cli.blazers.com
      - CORE_PEER_ADDRESS=supplier.blazers.com:7051
      - CORE_PEER_LOCALMSPID=BlazersMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - orderer_backend_network
    volumes:
        -  /var/run/:/host/var/run/
        - ./peer_files/:/opt/gopath/src/github.com/hyperledger/fabric/peer
        - ./msps/admin.blazers/msp:/etc/hyperledger/msp

networks:
  orderer_backend_network:
     external: true

volumes:
   retailer.blazers.com:
   
   manufacturer.blazers.com:

   supplier.blazers.com:

   distributor.blazers.com:

   admin.blazers.com:


   