OrdererOrgs:
- Name: Blazers
  Domain: blazers
  CommonName: blazers
  Specs:
  - Hostname: orderer.blazers
    CommonName: "{{.Hostname}}"
PeerOrgs:
- Name: Blazers
  Domain: blazers
  Specs:
  - Hostname: admin.blazers
    CommonName: "{{.Hostname}}"
  - Hostname: supplier.blazers
    CommonName: "{{.Hostname}}"
  - Hostname: distributor.blazers
    CommonName: "{{.Hostname}}"
  - Hostname: manufacturer.blazers
    CommonName: "{{.Hostname}}"
  - Hostname: retailer.blazers
    CommonName: "{{.Hostname}}"
